"""empty message

Revision ID: 115b3f916066
Revises: 
Create Date: 2021-04-19 11:30:40.045807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115b3f916066'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('Description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('mission_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missions')
    # ### end Alembic commands ###
