"""empty message

Revision ID: 20f19eb788c5
Revises: 583d721ed58a
Create Date: 2021-04-29 15:43:54.500402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f19eb788c5'
down_revision = '583d721ed58a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission_users', sa.Column('endDate', sa.DateTime(), nullable=True))
    op.add_column('mission_users', sa.Column('startDate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mission_users', 'startDate')
    op.drop_column('mission_users', 'endDate')
    # ### end Alembic commands ###
