"""empty message

Revision ID: 45e1bd5ec0b3
Revises: 7fb82b9f298b
Create Date: 2021-07-12 10:48:57.794347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e1bd5ec0b3'
down_revision = '7fb82b9f298b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lastdetach', sa.Column('driverId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lastdetach', 'driverId')
    # ### end Alembic commands ###
