"""empty message

Revision ID: 7fb82b9f298b
Revises: 20f19eb788c5
Create Date: 2021-06-11 10:57:58.971642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb82b9f298b'
down_revision = '20f19eb788c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('costs', sa.Column('DeviceID', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('costs', 'DeviceID')
    # ### end Alembic commands ###
