"""empty message

Revision ID: adf2352a19d0
Revises: 45e1bd5ec0b3
Create Date: 2021-07-19 14:16:57.320475

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'adf2352a19d0'
down_revision = '45e1bd5ec0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('histo_conductor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('histo_conductor',
    sa.Column('seq_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('CarId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('driverId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('added', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('removed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('seq_id', name='histo_conductor_pkey')
    )
    # ### end Alembic commands ###
