"""empty message

Revision ID: ba0f2761e691
Revises: 115b3f916066
Create Date: 2021-04-19 12:07:35.125656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0f2761e691'
down_revision = '115b3f916066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('Accomplie', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missions', 'Accomplie')
    # ### end Alembic commands ###
